#!/bin/bash

readonly DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# https://github.com/antlr/antlr4/blob/master/doc/getting-started.md
curl -O https://www.antlr.org/download/antlr-4.13.1-complete.jar

java -Xmx500M -cp "${DIR}/antlr-4.13.1-complete.jar:$CLASSPATH" \
     org.antlr.v4.Tool \
     -Dlanguage=Go \
     -visitor \
     -package parsing \
     -o "${DIR}/../pkg/parsing" \
     C.g4
